#spring:
#  redis:
#    uri: redis://default:SJOWdg4OdAv0trp5Yn2uShP21uX6uO0V@redis-14040.c264.ap-south-1-1.ec2.redns.redis-cloud.com:14040

spring:
  kafka:
    bootstrap-servers: pkc-l7pr2.ap-south-1.aws.confluent.cloud:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: weekly-sentiment-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: com.rahul.journal_app.model
    properties:
      security:
        protocol: SASL_SSL
      sasl:
        mechanism: PLAIN
        jaas:
#          config: org.apache.kafka.common.security.plain.PlainLoginModule required username='xxxxxxxxxxxxxxx' password='xxxxxxxxxxxxxxxx/Kj1xxD93A7r6x1jyb+TjGM2NXRpskInRsGfi/7MC0I9jHe';
          config: org.apache.kafka.common.security.plain.PlainLoginModule required username='6AJU7BDYERB3VQN3' password='7397U4OKSjuwcnd5/Kj1kL8D93A7r6x1jyb+TjGM2NXRpskInRsGfi/7MC0I9jHe';
      session:
        timeout:
          ms: 45000

  redis:
    host: redis-14040.c264.ap-south-1-1.ec2.redns.redis-cloud.com
    port: 14040
    password: SJOWdg4OdAv0trp5Yn2uShP21uX6uO0V

  mail:
    host: smtp.gmail.com
    port: 587
    username: rahul2148kumar@gmail.com
    password: cjbg orxj tesn qbnr
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  data:
    mongodb:
      uri: mongodb+srv://rahul2148kumar:iawyybB4QXIIUTD5@cluster0.vvonv.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0&ssl=true
      database: journaldb
      auto-index: true

#  profiles:
#    active: dev



weather:
  api:
    key: ef0096c229c46ce925ad9b29005d0044
    url: http://api.weatherstack.com/current?access_key=weatherApiKey&query=city

twitter:
  api:
    key: 4b75012982mshb827a1b5a697400p122c5ajsn25206f41ec7f
    host: twitter-api45.p.rapidapi.com
    url: https://twitter-api45.p.rapidapi.com/tweet.php?id=USER_ID

server:
  port: 8081
  servlet:
    context-path: /journal